#!/bin/bash

# This script takes some data generated by sensor-topology-gen.cpp
# and run the finishing-touch.cpp to create data for dtsim.cpp
# i: capital delta (maximum degree) of the graph
# j: variation of such density
# k: variation of sensor upload phase

for i in 3 9 15;
do
    for j in `seq 1 1 10`;
    do
        #for k in `seq 1 1 10`;
        for k in 1;
        do
            echo "../topos/${i}-${j}-${k}";
            # TODO: update the following to suit for your way of organizing files
            ./a.out ../topos-no-phase/d${i}-${j} > ../topos/${i}-${j}-${k};
            # sleep to avoid using the same time seed for pseudo-random-number generator
            sleep 1
        done
    done
done
